#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  baloyi97_frontend
        bind *:80
        mode http
        default_backend baloyi97_backend
backend baloyi97_backend
        balance roundrobin
        server 424061-web-01 34.227.92.127:80 check
        server 424061-web-02 34.224.6.201:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart the Nginx service
sudo service haproxy restart
